### ISSUE TITLE
Would it make sense to support no_std + alloc?

### ISSUE THREAD

**Issue by TheButlah** [smol-rs/async-executor#28] opened 2022-08-23 03:47 UTC
Would it make sense for this crate to support `no_std + alloc`? I thought of smol when searching for a async executor in embedded rust.

**Comment by notgull** [comment] 2022-08-23 14:22
This crate uses Mutexes to secure its interior data, so it would be difficult to port to `no_std`. That being said, I would accept a PR that replaces the mutexes if it doesn't show a regression, as long as it doesn't use spinlocks.

That being said `async_task` is `no_std`, so it might be better to build an executor abstraction around that.

**Comment by TheButlah** [comment] 2022-08-23 21:43
what is the difference between `async-executor` and `async_task`?

**Comment by notgull** [comment] 2023-01-23 17:52
I'm closing this for now, since we're not planning on moving in this direction. Thanks anyways!

**Closed** 2023-01-23 17:52 UTC

**Comment by TheButlah** [comment] 2023-01-23 18:08
FWIW i've been successfully using [`embassy`](https://embassy.dev/) for an embedded async executor.

**Comment by notgull** [comment] 2023-01-23 18:25
> FWIW i've been successfully using [`embassy`](https://embassy.dev/) for an embedded async executor.

Yes, I'd probably recommend `embassy` for most cases if you're using embedded targeted for `async`. Right now, in Stable Rust, it's probably not *impossible* to write a task/executor abstraction that works for both desktop and embedded, but it would be very hard and you'd end up with either a task abstraction that works well for embedded but not for desktop or vice versa.
